config/routes.rb
Rails.application.routes.draw do
  match '/customers/:customer_id/orders/:id/complete' => 'orders#complete', as: 'complete_order', via: :put 
  match '/customers/:customer_id/orders/:id/undo_complete' => 'orders#undo_complete', as: 'undo_complete_order', via: :put 
  match '/customers/:customer_id/orders/:id/cancel' => 'orders#cancel', as: 'cancel_order', via: :put 
  match '/customers/:customer_id/orders/:id/undo_cancel' => 'orders#undo_cancel', as: 'undo_cancel_order', via: :put
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :customers do
    resources :orders
  end
  namespace :api do 
    namespace :customer_portal_v1 do 
     resources :interests, only: [:index, :create]
    end 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  validates :email, presence: true
  validates :first_name, presence: true
  validates :address_line_1, presence: true
  validates :postcode, presence: true
end

app/models/interest.rb
class Interest < ApplicationRecord
  validates :postcode, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  validates :quantity, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :validatable
end

app/controllers/api/customer_portal_v1/interests_controller.rb
class Api::CustomerPortalV1::InterestsController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def index
    render json: Interest.all
  end

  def create
    interest = Interest.create(interest_params)
    render json: interest
  end

  private

  def interest_params
    params.require(:interest).permit(:first_name, :postcode, :email, :tel)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!, :check_staff
  before_action :set_customer, only: [:show, :edit, :update]

  def index
    check_staff
    @customers = Customer.all.order("created_at DESC")
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      # Tell the CustomerMailer to send a welcome email after save
      CustomerMailer.with(customer: @customer).welcome_email.deliver_later
      redirect_to @customer
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to customer_path(@customer), notice: 'Customer was successfully updated.'
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :address_line_1, :address_line_2, :town, :county, :postcode, :email, :tel)
  end

  def check_staff
    unless ["ollie@udderless.co.uk", "luke@udderless.co.uk", "barny@udderless.co.uk"].include?( current_user.email )
      redirect_to root_path, notice: "You are not one of the boys" 
    end
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :get_customer, :authenticate_user!, :check_staff
  before_action :set_order, only: [:show, :edit, :update, :destroy, :complete, :undo_complete, :cancel, :undo_cancel]

  # GET /orders
  # GET /orders.json
  def index
    @orders = @customer.orders.order("created_at DESC")
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = @customer.orders.build
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = @customer.orders.build(order_params)

    if @order.save
      # Tell the CustomerMailer to send an order confirmation email after save
      CustomerMailer.with(customer: @customer, order: @order).confirm_order.deliver_later
      redirect_to customer_orders_path(@customer), notice: 'Order was successfully created.' 
    else
      render :new 
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    if @order.update(order_params)
      redirect_to customer_order_path(@customer), notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    redirect_to customer_orders_path(@customer), notice: 'Order was successfully destroyed.'
  end

  def complete
    @order.completed = true
    @order.save
    redirect_to customer_orders_path(@customer)
  end

  def undo_complete
    @order.completed = false
    @order.save
    redirect_to customer_orders_path(@customer)
  end

  def cancel
    @order.cancelled = true
    @order.save
    redirect_to customer_orders_path(@customer)
  end

  def undo_cancel
    @order.cancelled = false
    @order.save
    redirect_to customer_orders_path(@customer)
  end

  private

  def check_staff
    unless ["ollie@udderless.co.uk", "luke@udderless.co.uk", "barny@udderless.co.uk"].include?( current_user.email )
      redirect_to root_path, notice: "You are not one of the boys" 
    end
  end

  def get_customer
    @customer = Customer.find(params[:customer_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = @customer.orders.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(:quantity, :customer_id, :frequency, :completed, :cancelled, :created_by)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/edit.html.erb
<div class="container">
  <div class="block">
    <h1 class="title">New Customer</h1>
    <%= form_for @customer do |form| %>
      <div class="field">
        <%= form.label "First Name", class: "label" %>
        <div class="control">
          <%= form.text_field :first_name, class: "input"%>
        </div>
      </div>
      <div class="field">
        <%= form.label "Last Name", class: "label" %>
        <div class="control">
          <%= form.text_field :last_name, class: "input" %>
        </div>
      </div>
      <div class="field">
        <%= form.label "Address Line 1", class: "label" %>
        <div class="control">
          <%= form.text_field :address_line_1, class: "input"%>
        </div>
      </div>
      <div class="field">
        <%= form.label "Address Line 2", class: "label" %>
        <div class="control">
          <%= form.text_field :address_line_2, class: "input" %>
        </div>
      </div>
      <div class="field">
        <%= form.label "Town/City", class: "label" %>
        <div class="control">
          <%= form.text_field :town, class: "input" %>
        </div>
      </div>
      <div class="field">
        <%= form.label "County", class: "label" %>
        <div class="control">
          <%= form.text_field :county, class: "input" %>
        </div>
      </div>
      <div class="field">
        <%= form.label "postcode", class: "label" %>
        <div class="control">
          <%= form.text_field :postcode, class: "input" %>
        </div>
      </div>
      <div class="field">
        <%= form.label "email", class: "label" %>
        <div class="control">
          <%= form.email_field :email, class: "input" %>
        </div>
      </div>
      <div class="field">
          <%= form.label "Telephone Number", class: "label" %>
        <div class="control">
          <%= form.text_field :tel, class: "input" %>
        </div>
      </div>
      <%= form.submit "Update", class: "button is-primary"  %>
    <% end %>
  </div>
</div>

app/views/customers/index.html.erb
<%= javascript_pack_tag 'hello_react' %>
<div>
  <%= link_to 'Add New Customer', new_customer_path, class: "button is-primary" %>
</div>
<section class="section">
  <% @customers[0..9].each do |customer| %>
    <% first_name = customer.first_name.nil? ? "" : customer.first_name %>
    <% last_name = customer.last_name.nil? ? "" : customer.last_name %>
    <% name = first_name + " " + last_name %>
    <div class="container">
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="subtitle is-4">
                <%= link_to name, customer %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %> 
</section>

app/views/customers/new.html.erb
<div class="container">
  <div class="block">
    <h1 class="title">New Customer</h1>
    <%= form_for @customer do |form| %>
      <div class="field">
        <%= form.label "First Name", class: "label" %>
        <div class="control">
          <%= form.text_field :first_name, class: "input"%>
        </div>
      </div>
      <div class="field">
        <%= form.label "Last Name", class: "label" %>
        <div class="control">
          <%= form.text_field :last_name, class: "input" %>
        </div>
      </div>
      <div class="field">
        <%= form.label "Address Line 1", class: "label" %>
        <div class="control">
          <%= form.text_field :address_line_1, class: "input"%>
        </div>
      </div>
      <div class="field">
        <%= form.label "Address Line 2", class: "label" %>
        <div class="control">
          <%= form.text_field :address_line_2, class: "input" %>
        </div>
      </div>
      <div class="field">
        <%= form.label "Town/City", class: "label" %>
        <div class="control">
          <%= form.text_field :town, class: "input" %>
        </div>
      </div>
      <div class="field">
        <%= form.label "County", class: "label" %>
        <div class="control">
          <%= form.text_field :county, class: "input" %>
        </div>
      </div>
      <div class="field">
        <%= form.label "postcode", class: "label" %>
        <div class="control">
          <%= form.text_field :postcode, class: "input" %>
        </div>
      </div>
      <div class="field">
        <%= form.label "email", class: "label" %>
        <div class="control">
          <%= form.email_field :email, class: "input" %>
        </div>
      </div>
      <div class="field">
          <%= form.label "Telephone Number", class: "label" %>
        <div class="control">
          <%= form.text_field :tel, class: "input" %>
        </div>
      </div>
      <%= form.submit "Create", class: "button is-primary"  %>
    <% end %>
  </div>
</div>

app/views/customers/show.html.erb
<div class="customer-style">
  <h1 class="subtitle content">
  Name: <%= @customer.first_name %> 
  <%= @customer.last_name %></h1>
  <h1 class="subtitle content">
    Address: 
    <div>
      <%= @customer.address_line_1 %><br />
      <%= @customer.address_line_2 %><br />
      <%= @customer.town %><br />
      <%= @customer.county %><br />
      <%= @customer.postcode %><br />
    </div>
  </h1>
  <h1 class="subtitle content">Email: <%= @customer.email %></h1>
  <h1 class="subtitle content">Phone: <%= @customer.tel %></h1>

  <div class="button is-primary">
    <%= link_to "New Order", new_customer_order_path(@customer) %>
  </div>

  <div class="button is-primary">
    <% button_badge = @customer.first_name + "'s Orders" %>
    <%= link_to button_badge, customer_orders_path(@customer) %>
  </div>
  <div class="button is-primary">
    <%= link_to "Edit Customer Details", edit_customer_path(@customer) %>
  </div>
</div>

app/views/home/index.html.erb
<%= javascript_pack_tag 'hello_react' %>
<% name = current_user.present? ? current_user.email : 'Stranger' %>
<section class="section">
  <div class="container">
    <h1 class="title">
      Welcome, <%= name %>
    </h1>
    <%= image_tag("TM-logo.gif") %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>UdderlessManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.0.0/mapbox-gl.css' rel='stylesheet' />
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
    <%= favicon_link_tag asset_path('TM-logo.gif') %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/orders/edit.html.erb
<%= javascript_pack_tag 'order_form' %>

<h1 class="title">New Order</h1>
<div class="control">
  <button id="one-off">
    One Off
  </button>
  <button id="continuous">
    Continuous
  </button>
</div>

<div id="one-off-form" class="form">
  <%= form_with(model: [@customer, @order]) do |form| %>
    <div class="field">
      <%= form.label "Quantity", class: "label" %>
      <div class="control">
        <%= form.text_field :quantity, class: "input"%>
      </div>
    </div>
    <%= form.submit "Create", class: "button is-primary"  %>
  <% end %>
</div>
<div id="continuous-form" class="form">
  <%= form_with(model: [@customer, @order]) do |form| %>
    <div class="field">
      <%= form.label "Quantity", class: "label" %>
      <div class="control">
        <%= form.text_field :quantity, class: "input"%>
      </div>
    </div>
    <div class="field">
      <%= form.label "Frequency", class: "label" %>
      <div class="control">
        <%= form.text_field :frequency, class: "input"%>
      </div>
    </div>
    <%= form.submit "Update", class: "button is-primary"  %>
  <% end %>
</div>

app/views/orders/index.html.erb
<section class="section">
  <div class="button is-primary">
    <%= link_to "Back To #{@customer.first_name}", customer_path(@customer) %>
  </div>
  <% @orders[0..9].each do |order| %>
    <div class="container">
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="subtitle is-4">
                <% if order.completed == true %>
                <%   status = "Completed" %>
                <% else %>
                <%   status = order.cancelled ? "Cancelled" : "Not Completed" %>
                <% end %>
                <% link_badge = "Order Number: " + order.id.to_s + order.created_at.strftime(" | Created on %m/%d/%Y  at %I:%M%p").to_s + " | Status: " + status %>
                <%= link_to link_badge, customer_order_path(@customer.id, order.id) %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %> 
</section>

app/views/orders/new.html.erb
<%= javascript_pack_tag 'order_form' %>
<div class="order-style">
  <h1 class="title">New Order</h1>
  <div class="control">
    <button id="one-off">
      One Off
    </button>
    <button id="continuous">
      Continuous
    </button>
  </div>
</div>


<div id="one-off-form" class="form order-style">
  <%= form_with(model: [@customer, @order]) do |form| %>
    <div class="field">
      <%= form.label "Quantity", class: "label" %>
      <div class="control">
        <%= form.text_field :quantity, class: "input"%>
      </div>
    </div>
    <%= form.submit "Create", class: "button is-primary"  %>
  <% end %>
</div>
<div id="continuous-form" class="form order-style">
  <%= form_with(model: [@customer, @order]) do |form| %>
    <div class="field">
      <%= form.label "Quantity", class: "label" %>
      <div class="control">
        <%= form.text_field :quantity, class: "input"%>
      </div>
    </div>
    <div class="field">
      <%= form.label "Frequency", class: "label" %>
      <div class="control">
        <%= form.text_field :frequency, class: "input"%>
      </div>
    </div>
    <div class="field">
      <div class="control">
        <%= form.hidden_field :created_by, class: "input", value: current_user.email%>
      </div>
    </div>
    <%= form.submit "Create", class: "button is-primary"  %>
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="order-style">
  <h1 class="title">Order No. <%= @order.id %></h1>
  <h1>Created at: <%= @order.created_at %></h1>
  <h1>Created by: <%= @order.created_by %></h1>
  <h1>Quantity: <%= @order.quantity %></h1>
  <h1>Frequency: <%= @order.frequency %></h1>
  <h1>Customer ID: <%= @order.customer_id %></h1>
  <h1>Customer name: <%= @customer.first_name %> <%= @customer.last_name %></h1>
  <h1>Customer address: 
    <div>
      <%= @customer.address_line_1 %><br />
      <%= @customer.address_line_2 %><br />
      <%= @customer.town %><br />
      <%= @customer.county %><br />
      <%= @customer.postcode %><br />
    </div>
  </h1>
  <h1>Customer email: <%= @customer.email %></h1>
  <h1>Customer phone: <%= @customer.tel %></h1>
  <% if @order.completed == true %> 
    <div class="button is-primary">
      <%= link_to "Undo Complete Order", undo_complete_order_path(@customer, @order), method: :put %>
    </div>
  <% else %>
    <div class="button is-primary">
      <%= link_to "Complete", complete_order_path(@customer, @order), method: :put %>
    </div>
  <% end %>
  <% if @order.cancelled == true %> 
    <div class="button is-primary">
      <%= link_to "Undo Cancel Order", undo_cancel_order_path(@customer, @order), method: :put %>
    </div>
  <% else %>
    <div class="button is-primary">
      <%= link_to "Cancel Order", cancel_order_path(@customer, @order), method: :put %>
    </div>
  <% end %>
  <div class="button is-primary">
    <%= link_to "Edit", edit_customer_order_path(@customer, @order), method: :get %>
  </div>
  <div class="button is-primary">
    <%= link_to "Delete", customer_order_path(@customer, @order), method: :delete, data: { confirm: "Are you sure?" }%>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <%= image_tag("TM-logo.gif") %>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">

      <a class="navbar-item">
        <div class="subtitle">
          <%= link_to 'Customers', customers_path %>
        </div>
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
          <div class="button is-primary">
            <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
          </div>
          <% else %>
            <% if !current_page?('/users/sign_up') %>
            <div class="button is-primary">
              <%= link_to 'Sign Up', new_user_registration_path %>
            </div>
            <% end %>
          <div class="button is-primary">
            <%= link_to 'Log in', new_user_session_path %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav> 